name: barsync
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  print_bluetooth_thermal: ^1.1.6
  flutter_blue_plus: ^1.35.4
  # esc_pos_printer_plus: ^0.1.1
  # esc_pos_utils_plus: ^2.0.4        
  # multicast_dns: ^0.3.2
  another_flushbar: ^1.12.30
  pdf: ^3.10.8
  printing: ^5.12.0 
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.7
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  cloud_functions: ^5.5.0
  flutter_local_notifications: ^19.2.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/barSyncApp.png"